spring:
  mail:
    host: smtp.peso.co.kr
    port: 25
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devlivego1?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: devlivego@5279
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  ssl:
    port: 9001
    enabled: true
    key-store: /home/devlivego/sslkey/Wildcard.testpeso.com_jks.jks
    key-store-type: JKS
    key-store-password: '#*.testpeso.com@'

